apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-stack
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: infra
  path: ./monitoring/stack

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-app
  namespace: flux-system
spec:
  dependsOn:
    - name: monitoring-stack
  interval: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: infra
  path: ./monitoring/app
