stages: [lint, deploy]

default:
  tags: ["main"]   # запускаем джобы на твоём runner'е с тегом main

.helm_base:
  image: alpine/helm:3.14.4
  before_script:
    - apk add --no-cache kubectl ca-certificates
    # из B64 в файл, который kubectl увидит по $KUBECONFIG
    - echo "$KUBECONFIG_B64" | base64 -d > "$KUBECONFIG"
    - test -s "$KUBECONFIG" || (echo "empty kubeconfig" && exit 2)
    - kubectl version --client=true
    - kubectl cluster-info

# дымовой тест, чтобы сразу увидеть проблемы с доступом к API
smoke_kube:
  stage: lint
  extends: .helm_base
  script:
    - kubectl get ns
  rules:
    - if: $CI_COMMIT_BRANCH

helm_lint:
  stage: lint
  extends: .helm_base
  script:
    - helm lint charts/myapp
  rules:
    - if: $CI_COMMIT_BRANCH

helm_deploy_dev:
  stage: deploy
  extends: .helm_base
  variables:
    HELM_RELEASE: ${HELM_RELEASE:-myapp}
    HELM_NAMESPACE: ${HELM_NAMESPACE:-dev}
    IMAGE_REPO: ${IMAGE_REPO:-registry.gitlab.com/georgiiwinistr1977-group/app}
    IMAGE_TAG: ${IMAGE_TAG:-latest}
  script:
    - kubectl get ns "$HELM_NAMESPACE" || kubectl create ns "$HELM_NAMESPACE"
    - >
      helm upgrade --install "$HELM_RELEASE" charts/myapp
      --namespace "$HELM_NAMESPACE"
      --set-string image.repository="$IMAGE_REPO"
      --set-string image.tag="$IMAGE_TAG"
      --atomic --wait --timeout 5m
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
