apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-stack
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
  path: ./infra/monitoring/stack
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-app
  namespace: flux-system
spec:
  dependsOn:
    - name: monitoring-stack
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
  path: ./infra/monitoring/app
  wait: true
