# charts/myapp/values.yaml
image:
  repository: 192.168.0.10:5050/root/app   # ← твой GitLab Registry
  tag: "latest"                             # или конкретный тег из app-пайплайна
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: regcred                           # секрет с доступом к реестру (в ns dev)

replicaCount: 1

service:
  port: 8080
  type: ClusterIP

config:
  PING_RESPONSE: "pong"
  LOG_LEVEL: "info"

secret:
  enabled: true
  data:
    DB_USER: "demo"
    DB_PASSWORD: "demo-pass"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  metrics:
    cpu:
      averageUtilization: 60
    memory:
      averageUtilization: 70
