apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prom-stack
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      # Зафиксируй версию чартов под твой репозиторий, пример:
      # version: 60.2.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system   # ВАЖНО: где создан HelmRepository
  install:
    createNamespace: true
    crds: Create                 # ВАЖНО: поставить CRD (PrometheusRule и т.п.)
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace          # ВАЖНО: обновлять CRD при апгрейде
    remediation:
      retries: -1

  values:
    grafana:
      admin:
        existingSecret: grafana-admin
        existingSecretKey: admin-password
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - grafana.local
        path: /
        pathType: Prefix
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
        datasources:
          enabled: true

    prometheus:
      prometheusSpec:
        retention: 7d
        # Пустые селекторы = матчить все объекты данного типа
        serviceMonitorSelector: {}
        podMonitorSelector: {}
        ruleSelector: {}
        # Эти три позволяют собирать объекты из ЛЮБОГО namespace
        serviceMonitorNamespaceSelector: {}
        podMonitorNamespaceSelector: {}
        ruleNamespaceSelector: {}

    kubeStateMetrics:
      enabled: true
    nodeExporter:
      enabled: true
