apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepo.yaml          # namespace: flux-system внутри файла!
  - grafana-admin-secret.yaml
  - helmrelease.yaml